// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbFyFOP8fufPzUy5vOa8S07SEwVB3b79I',
    appId: '1:268236149930:web:b5e445a7fcb20526b6acd3',
    messagingSenderId: '268236149930',
    projectId: 'mynotes-sandeep103',
    authDomain: 'mynotes-sandeep103.firebaseapp.com',
    storageBucket: 'mynotes-sandeep103.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlLDWvGKzXHyJmk7TWwsbL3bqCcBs0XtE',
    appId: '1:268236149930:android:b312cd5f2348c887b6acd3',
    messagingSenderId: '268236149930',
    projectId: 'mynotes-sandeep103',
    storageBucket: 'mynotes-sandeep103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLIXY4KPR0GKz9duTYirFhnphgLxifJ2s',
    appId: '1:268236149930:ios:0b19fe352844bb21b6acd3',
    messagingSenderId: '268236149930',
    projectId: 'mynotes-sandeep103',
    storageBucket: 'mynotes-sandeep103.appspot.com',
    iosClientId: '268236149930-legufb9mckbsuok0qh0tb4l3r9cfeq1m.apps.googleusercontent.com',
    iosBundleId: 'com.sandeep.mynotes2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLIXY4KPR0GKz9duTYirFhnphgLxifJ2s',
    appId: '1:268236149930:ios:ff91996dee5f445cb6acd3',
    messagingSenderId: '268236149930',
    projectId: 'mynotes-sandeep103',
    storageBucket: 'mynotes-sandeep103.appspot.com',
    iosClientId: '268236149930-mhhf2eija9rgp0t8evgb2ausbpvvitp6.apps.googleusercontent.com',
    iosBundleId: 'com.sandeep.mynotes2.RunnerTests',
  );
}
